### ISSUE TITLE
Color picker with suport for opacity

### ISSUE THREAD

**Issue by Bamajon1974** [Andreto/Custom-Highlight#1]
Feature requests:  ability to change opacity of text and background color. 
Additionally, when clicking on the background and text color box, ability to chose a color from a popup window in addition to entering hex code rgb numbers. Thanks in Advance!

**Comment by Andreto** [comment]
Pretty much done. I will probably push an update later this week.

**Comment by Bamajon1974** [comment]
Wow! That was quick. Thank you. Please shoot an email my way when you push
the update.

Thanks, Jon

**Comment by Andreto** [comment]
Uploaded to chrome web store.
