### ISSUE TITLE
Doesn't work for PDF viewing in Browser

### ISSUE THREAD

**Issue by gnuarm** [Andreto/Custom-Highlight#12]
I'm looking for a way to change the search highlight color for PDF files in Chrome.   I thought I was having trouble with this in the PDF file, but it's not working for web pages either.  Maybe I don't understand how it works.  I installed the extension, set a color (bright green), the did a search.  The search highlight colors are still orange for the item selected and yellow for other found items, but not the current selection.

**Comment by Andreto** [comment]
This extension changes the color of the highlight that appear when you select content on the webpage with the cursor. Creating a Chrome-extension that changes the search-highligt is as far as i know not possible since the search is a part of Chrome and not the webpage.
