### ISSUE TITLE
Dark reader compatibility

### ISSUE THREAD

**Issue by Andreto** [Andreto/Custom-Highlight#3]
When [dark reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) is activated the highlight color goes back to the normal one.

No solution yet.

**Comment by Andreto** [comment]
c88930f

**Comment by mc-marcocheng** [comment]
![Capture](https://user-images.githubusercontent.com/57459045/103462957-dbd1e880-4d63-11eb-835f-307b1e5d0a86.PNG)
The colors do not match when dark reader is on and lighter colors are chosen.

**Comment by Andreto** [comment]
@mc-marcocheng 
I found the issue. It seems like dark-reader applies an additional styling element that isn't affected by the current overriding method. This might be a new thing but I'm not sure. This can be solved by simply adding a `!important` rule to the injected style but I would like to avoid using this kind of aggressive overwriting for accessibility reasons.

I also think that the colors that dark-reader sets for the highlight look very good and are easy to read so I would definitely like to have the option the extension to keep these dynamic dark-mode colors. 

I will see if I can find a better way around the issue, and hopefully, I'll be able to push an update in the near future.

**Comment by Andreto** [comment]
Still working on this, turns out it was a bit harder then expected. https://github.com/Andreto/Custom-Highlight/commit/7cc9c16f7eb3e79b9da249faaa5b0404e3f97d73

**Comment by mc-marcocheng** [comment]
Not sure if it is related, but I had posted this issue on [](https://github.com/darkreader/darkreader/issues/484#issuecomment-753574551). They say that it is related to my custom theme settings, but I don't know what theme of mine that caused this behavior.

**Comment by mc-marcocheng** [comment]
Not sure if it is related, but I had posted this issue on [.](https://github.com/darkreader/darkreader/issues/484#issuecomment-753574551) They say that it is related to my custom theme settings, but I don't know what theme of mine that caused this behavior.

**Comment by mc-marcocheng** [comment]
Not sure if it is related, but I had posted this issue on https://github.com/darkreader/darkreader/issues/484#issuecomment-753574551 . They say that it is related to my custom theme settings, but I don't know what theme of mine that caused this behavior.

**Comment by Andreto** [comment]
I can't quite get it right. Overwriting the dark reader colors now works on most sites but not on Github for some reason. I've also added options to not overwrite the dark reader as mentioned earlier. Also apparently really light colors will become slightly darker on a dark background. This is not dark readers' fault, it's just how highlight-text is rendered apparently.

I will not push this update to the webstore just yet but if you want to try it out you could download the source code and load it as an unpacked extension.

@mc-marcocheng

**Comment by mc-marcocheng** [comment]
![image](https://user-images.githubusercontent.com/57459045/105571275-c6ac1080-5d89-11eb-900b-2aa74763db56.png)
1. For some reason I just can't get the color of the highlight color right.
2. There is about 10% chance that the colors in the preview windows are rendering the default colors when I open the popup window.
3. The "More info" button doesn't work?

Not sure if this is related, but I had posted an issue on https://github.com/darkreader/darkreader/issues/484#issuecomment-753574551 . They say that it is due to my custom theme settings. But I have no idea which theme of mine that causes the issue.

**Comment by Andreto** [comment]
@mc-marcocheng 
1. Could you explain a bit more?
2. Known issue #7, this only seem to happen when running the extension as unpacked. Had this issue when testing the last published update, but when published to the web store the issue disappeard.
3. Yeah, forgot about that one. I was about to make a page on the site that explains these ones.

**Comment by mc-marcocheng** [comment]
As you can see from my screencap, the text highlight color is a bit darker than the one shown in the popup page. Pressing the Dynamic color checkbox only makes it even darker.
Perhaps this is because of my custom theme settings.

**Comment by Andreto** [comment]
Unfortunately, there is no way to change this. That's just how to highlight color is rendered on dark backgrounds. Go to [this js fidle,](https://jsfiddle.net/Andreto/ju5f9xzb/4/) turn off darkreader and Custom-Highlight, and try to select the "try to select this text". The highlight is set to have a white background and blue text but the background renders as grey.

The dynamic color checkbox uses darkreaders' interpretation of your color choice. Maybe this should be clarified a bit more.

**Comment by Andreto** [comment]
[v1.4.3](https://github.com/Andreto/Custom-Highlight/releases/tag/v1.4.3) is now published with the dark reader improvements and more. 

To prevent the dark reader from changing the highlight color turn 
_Dynamic color (Dark Reader)_ **off** 
and 
_Aggressive overwrite_ **on**

I will close this issue for now.
