### ISSUE TITLE
Feature Request: Change live search / quick find color (when pressing ctrl + F)

### ISSUE THREAD

**Issue by mylesmc123** [Andreto/Custom-Highlight#5]
Currently, the live search and quick find color in chrome is yellow with orange for the current selection in the find range. For example, if you Ctrl + F and search for the term: 'search' it will come up with multiple results, all the results will be highlighted yellow except the currently focused item, The find UI can scroll through the search results changing the focused item to orange and scrolling the page.

The Yellow / Orange color scheme is difficult to see on dark-mode / low-contrast pages, so being able to edit these colors would be very beneficial and a great new feature to the Custom-Highlight extension.

Adding this issue, as I found the chrome extension from trying to find this specific feature and saw a comment on possibly adding it in this forum: https://superuser.com/questions/854378/how-to-change-chrome-highlight-color

**Comment by Andreto** [comment]
I have looked into it and unfortunately, it seems like it can't be done in an easy way. The find tool does not change the page content, and therefore it's not accessible by chrome extensions. 

I will close this issue for now but if I ever find a solution I will get back on it.

**Comment by sisrfeng** [comment]
Year 2022 now, any update?
The yellow is sooooooooooooooooo ugly

**Comment by Andreto** [comment]
> Year 2022 now, any update?
> The yellow is sooooooooooooooooo ugly

The situation is still the same.
